<a href="https://colab.research.google.com/github/devbispo/curso-python/blob/main/Aprendizagem_de_m%C3%A1quina_Tratamento_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Encontrando valores incosistentes na idade
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
base.describe()
base.loc[base['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [2]:
# Removendo a coluna idade (Nào recomendado)
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
base.drop('age', 1, inplace=True)
base.describe()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """

          clientid        income          loan      default
count  2000.000000   2000.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018   4444.369695     0.141500
std     577.494589  14326.327119   3045.410024     0.348624
min       1.000000  20014.489470      1.377630     0.000000
25%     500.750000  32796.459717   1939.708847     0.000000
50%    1000.500000  45789.117313   3974.719419     0.000000
75%    1500.250000  57791.281668   6432.410625     0.000000
max    2000.000000  69995.685578  13766.051239     1.000000

In [4]:
#Apagando somente os registros com problema(nào recomendado)
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
base.drop(base[base.age < 0].index, inplace=True)
base.loc[base['age'] < 0]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []

In [5]:
#substituindo as idades com problema pela média das idades corretas 
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
base.mean()
print('Média:', base['age'][base.age > 0].mean()) #Média total das idades 

base.loc[base.age < 0, 'age'] = base['age'][base.age>0].mean() 
base.loc[base['age']<0]
print(base.loc[[15]])
print(base.loc[[21]])
print(base.loc[[26]])

Média: 40.92770044906149
    clientid        income      age         loan  default
15        16  50501.726689  40.9277  3977.287432        0
    clientid        income      age         loan  default
21        22  32197.620701  40.9277  4244.057136        0
    clientid        income      age         loan  default
26        27  63287.038908  40.9277  9595.286289        0

In [6]:
#iloc é para dividir 
#[todas as linhas, colunas 1, 2 e 3 (0 de id desconsiderado)]
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values
print(previsores)

[[6.61559251e+04 5.90170151e+01 8.10653213e+03]
 [3.44151540e+04 4.81171531e+01 6.56474502e+03]
 [5.73171701e+04 6.31080495e+01 8.02095330e+03]
 ...
 [4.43114493e+04 2.80171669e+01 5.52278669e+03]
 [4.37560566e+04 6.39717958e+01 1.62272260e+03]
 [6.94365796e+04 5.61526170e+01 7.37883360e+03]]

In [17]:
from numpy.ma.core import mean
import pandas as pd
import numpy as np
base = pd.read_csv('credit_data.csv')
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values
print(np.argwhere(np.isnan(previsores)))#posicào de valores faltantes
print(previsores[np.argwhere(np.isnan(previsores))[0][0],:])
print(previsores[np.argwhere(np.isnan(previsores))[1][0],:])
print(previsores[np.argwhere(np.isnan(previsores))[2][0],:])
from sklearn.impute import SimpleImputer # subtituir nulos pela média
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(previsores[:,0:3])
previsores[:, 0:3] = imputer.transform (previsores [:, 0:3])
print(np.argwhere(np.isnan(previsores)))
print (previsores[28,:])

[[28  1]
 [30  1]
 [31  1]]
[59417.80540626            nan  2082.62593812]
[48528.85279572            nan  6155.78467026]
[23526.30255511            nan  2862.01013875]
[]
[5.94178054e+04 4.08075594e+01 2.08262594e+03]

In [ ]:
______________________________
______________________________

In [14]:
from numpy.ma.core import mean
import pandas as pd
import numpy as np
base = pd.read_csv('census.csv')
previsores = base.iloc[:, 0:14].values
classe = base.iloc[:, 14].values
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehorencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])],remainder='passthrough')
previsores = OneHotEncoder.fit_transform(previsores).toarray()
print(previsores[0:10, :])

TypeError: ignored